### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by AnnAddicks** [AnnAddicks/ToastmasterAgenda#1]
I need the following documentation added to README.md:

- Add the format expected from the the way the google document is laid out. The document can be found here:  https://docs.google.com/spreadsheets/d/1_P9K2asfsITSGEAh7PrPLxncSemNnjXHg3_O3q7OW0k/edit?usp=sharing

For example, line one is the date, line two is the Toastmaster of the Day, etc.  If you can, copy and paste the way the cells look.

_This issue has been created for a participant the "Commit To Open Source Today!" talk at We Rise Women in Tech Conference._

**Comment by propupul** [comment]
I added to the README.md but it doest not look right. I will fix it. Thanks

**Comment by AnnAddicks** [comment]
Hi!  I'm glad you are working on this.  Let me know if you need some guidance.  Currently, the changes you made are on your local repository.  When you are happy with the changes, you can submit a pull request:  https://help.github.com/articles/creating-a-pull-request/

Let me know if you need help, I'm here or available on the WWC slack.
Thanks!!!

**Comment by AnnAddicks** [comment]
Actually, this link may be more relevant:  https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by AnnAddicks** [comment]
Fixed by @propupul in pull request https://github.com/AnnAddicks/ToastmasterAgenda/pull/6

**Comment by AnnAddicks** [comment]
:cake:
