### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by AnnAddicks** [AnnAddicks/ToastmasterAgenda#11]
A JokeMaster has been added to the Agenda.  This means the Readme.md needs to be updated.  Under form layout two things need to change:

1. Add a new row for Joke Master right after Toastmaster of the day (row # 3).
2. Add 1 to each row after this new row.  Example:  General Evaluator is now row # 4

**Comment by Doommarine23** [comment]
I don't mind helping out 👍

**Comment by AnnAddicks** [comment]
Fixed by @Doommarine23.  Thanks for your help :cake:
