### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by AnnAddicks** [AnnAddicks/ToastmasterAgenda#13]
The Google Spreadsheet was changed to remove the whitespace rows.  The README.md file needs to be updated  to reflect this change.  Rows 8, 17, 19, 21 need to be removed and the row numbers updated.

**Comment by Ph4n4l4x** [comment]
I'll take this issue.
EDIT: Have opened a pull request.

**Comment by AnnAddicks** [comment]
Fixed by @Aerisu, thanks!  :cake:
