### ISSUE TITLE
Add Documentation

### ISSUE THREAD

**Issue by AnnAddicks** [AnnAddicks/ToastmasterAgenda#2]
I need the documentation added to README.md something along the lines of:

 
- To change google docs sheets make sure your sheet is publicly readable with a link.
- Copy the highlighted spreadsheet identifier found on the shareable link: https://docs.google.com/spreadsheets/d/1_P9K2asfsITSGEAh7PrPLxncSemNnjXHg3_O3q7OW0k/edit?usp=sharing and add it to file Sheets.go.  For my Google Spreadsheet it is **1_P9K2asfsITSGEAh7PrPLxncSemNnjXHg3_O3q7OW0k**.

**Comment by namansancheti** [comment]
Hi @AnnAddicks,
I have created a Pull Request with the request changes as per Issue 2.
This is my first time making a PR, so please let me know, if there is something I did incorrectly.

Thanks,
Naman

**Comment by AnnAddicks** [comment]
Fixed by @namansancheti!
