### ISSUE TITLE
Update to 2017-2018 Agenda

### ISSUE THREAD

**Issue by AnnAddicks** [AnnAddicks/ToastmasterAgenda#3]
Sheets.go is now fetching an old spreadsheet.  Update the spreadsheet on this line

`service.FetchSpreadsheet("1_P9K2asfsITSGEAh7PrPLxncSemNnjXHg3_O3q7OW0k/")`

to reference the new one located here: 
 https://docs.google.com/spreadsheets/d/1CBlORqCzL6YvyAUZTk8jezvhyuDzjjumghwGKk5VIK8/edit?usp=sharing.  Use **1CBlORqCzL6YvyAUZTk8jezvhyuDzjjumghwGKk5VIK8**

_This issue has been created for a participant the "Commit To Open Source Today!" talk at We Rise Women in Tech Conference._

**Comment by Darkpingouin** [comment]
I think the issue can be closed now because the concerned code has been updated :smile:

**Comment by AnnAddicks** [comment]
I agree, @ingrid02  fixed this issue.  Thanks @Darkpingouin!
