### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by AnnAddicks** [AnnAddicks/ToastmasterAgenda#8]
README.md needs to add a new header section on how to build this project.  Under how to build, it needs go version 1.7.4 or higher.  It also needs to demonstrate client_secret.json. Repeat what Iwark says in https://github.com/Iwark/spreadsheet/tree/v2#preparation in our docs.

**Comment by Logan1x** [comment]
Can you describe more on what project you are talking about. I saw nothing but tables in readme.md what do you want to add in this?? @AnnAddicks

**Comment by AnnAddicks** [comment]
Hi @Logan1x, thanks for asking for clarification.  The readme.md is displayed after the code section on the repo's main page:  https://github.com/AnnAddicks/ToastmasterAgenda and you are right there is a big section of table under the Form Layout header.  I need this doc to go above this section or below the  Note header section.  If you need more clarification, feel free to ask.

**Comment by Logan1x** [comment]
Hi @AnnAddicks  Created PR #9 After changes if you want something else tag me.

**Comment by AnnAddicks** [comment]
Hi @Logan1x, those changes look fine and can be merged.  

The purpose for this issue is to add information about a hidden file:  client_secret.json.  I need a new header section for how to build the project.  The information about the hidden file is found here:  https://github.com/Iwark/spreadsheet/tree/v2#preparation 

Let me know if you have more questions.  
Thanks!

**Comment by austinjcheng** [comment]
I believe I managed to complete the pull request, but if I'm missing anything please let me know.

**Comment by AnnAddicks** [comment]
Code merged, thanks for your help!
